### ISSUE TITLE
rebuild

### ISSUE THREAD

**Issue by ghost** [PengBAI/docker-oracle-12c-R1#1]
Hi, i tried to rebuild the image. i modified the startup.sh

but the build failed at install.sh
docker version 1.12.1
CentOS 7.2
had enough disk > 20GB

`Step 8 : RUN /scripts/install.sh
 ---> Running in ac992515d21c
Initializing database.
Copying database files
1% complete
2% complete
4% complete
DBCA Operation failed.
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/xe/xe.log" for further details.
\n\n\n\n

Unique database identifier check passed.

/ has enough space. Required space is 6140 MB , available space is 22645 MB.
File Validations Successful.
Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 2%
ORA-00821: Specified value of sga_target 384M is too small, needs to be at least 400M
ORA-01078: failure in processing system parameters

DBCA_PROGRESS : 4%
ORA-01034: ORACLE not available

ORA-01034: ORACLE not available

DBCA_PROGRESS : DBCA Operation failed.
The command '/bin/sh -c /scripts/install.sh' returned a non-zero code: 1`

workaround was to increase the DBCA_TOTAL_MEMORY to 1024

**Comment by PengBAI** [comment]
OK I will fix it with DBCA_TOTAL_MEMORY=1024, 
Thank you
